import { join } from "node:path";

import { describe, expect, it } from "vitest";

import { parseCLIArguments } from "../src/cliArguments.js";

const uuidPattern =
  /^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/;

function renderCommand(
  parsed: Awaited<ReturnType<typeof parseCLIArguments>>,
): Extract<typeof parsed, { command: "render" }> {
  if (parsed.command !== "render") throw new Error("Expected render command");
  return parsed;
}

function outputPath(
  output: Extract<
    Awaited<ReturnType<typeof parseCLIArguments>>,
    { command: "render" }
  >["options"]["outputs"][number],
): string | undefined {
  return "path" in output && typeof output.path === "string"
    ? output.path
    : undefined;
}

describe("CLI output defaults", () => {
  it("generates a recognizable unique PNG destination when --out is omitted", async () => {
    const first = renderCommand(
      await parseCLIArguments(["art/My Café.scene.mjs"]),
    );
    const second = renderCommand(
      await parseCLIArguments(["render", "art/My Café.scene.mjs"]),
    );

    expect(first.renderId).toMatch(uuidPattern);
    expect(second.renderId).toMatch(uuidPattern);
    expect(second.renderId).not.toBe(first.renderId);
    expect(first.source).toBe("art/My Café.scene.mjs");
    expect(second.source).toBe(first.source);
    expect(first.options.outputs).toHaveLength(1);
    expect(first.options.outputs[0]?.format).toBe("png");
    expect(outputPath(first.options.outputs[0]!)).toBe(
      join("pts-output", "My-Cafe.scene-" + first.renderId + ".png"),
    );
  });

  it("uses --format for an autogenerated output", async () => {
    const parsed = renderCommand(
      await parseCLIArguments([
        "render",
        "scene.mjs",
        "--format",
        "svg",
        "--text-mode",
        "outline",
      ]),
    );

    expect(parsed.options.outputs).toEqual([
      {
        path: join("pts-output", "scene-" + parsed.renderId + ".svg"),
        format: "svg",
        textMode: "outline",
      },
    ]);
  });

  it("generates a filename inside an explicit trailing-slash directory", async () => {
    const parsed = renderCommand(
      await parseCLIArguments([
        "render",
        "scene.mjs",
        "--out",
        "renders/",
        "--format",
        "jpg",
      ]),
    );

    expect(parsed.options.outputs).toEqual([
      {
        path: join("renders", "scene-" + parsed.renderId + ".jpeg"),
        format: "jpeg",
      },
    ]);
  });

  it("preserves exact output paths and rejects a value-less --out", async () => {
    const explicit = renderCommand(
      await parseCLIArguments(["scene.mjs", "--out", "art.png"]),
    );
    expect(explicit.options.outputs).toEqual([
      { path: "art.png", format: "png" },
    ]);

    await expect(
      parseCLIArguments(["render", "scene.mjs", "--out", "--json"]),
    ).rejects.toMatchObject({ code: "CLI_USAGE", phase: "arguments" });

    await expect(
      parseCLIArguments(["one.mjs", "two.mjs"]),
    ).rejects.toMatchObject({ code: "CLI_USAGE", phase: "arguments" });
  });
});
